### ISSUE TITLE
** UPDATE TO BUG ** in Metronome Auction

### ISSUE THREAD

**Issue by rsostrow91** [autonomoussoftware/documentation#25]
I purchased some MET at the Metronome Auction and while I was waiting for miner confirmation I started getting a string of error messages that eventually filled two windows. 

I have attached three files to this issue so that you can help me.
1) **My Wallet.jpg** which shows the state of my wallet after my purchase.
2) **Purchase Transaction.jpg** which shows the actual transaction with 
    numbers that can be traced back to your system.
3) **Metronome Error Messages.txt** which is a Notepad (*.txt) file that 
    shows one half of the error messages I received. Double-click on the
    name of the file. It will download and you can open it if you have to.
Please contact me and help me to clear up this mess. 

Richard Ostrow 
**<rostrow@anyarch.net>**
(914) 420-2765 - **CALL ANYTIME UP TILL 3:00 AM EST ELSE TOMORROW**
Please help.
Thanks in advance. Rick Ostrow
![my wallet transaction](https://user-images.githubusercontent.com/40405691/41831381-ab09f016-7814-11e8-9d87-c8d987b22d98.jpg)
![purchase transaction](https://user-images.githubusercontent.com/40405691/41831383-b2fd9a70-7814-11e8-9650-89034371eff9.jpg)
[Metronome Error Messages.txt](https://github.com/autonomoussoftware/documentation/files/2131797/Metronome.Error.Messages.txt)

**Comment by jgarzik** [comment]
Looks like toLowerCase error:

Pasting,
```
Unhandled Error
TypeError: Cannot read property 'toLowerCase' of undefined
at getAuctionAddress (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/plugins/metronome/settings.js:6:47)
at sendStatus (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/plugins/metronome/status.js:19:54)
at C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/plugins/metronome/index.js:25:5
at Array.forEach (<anonymous>)
at C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/plugins/metronome/index.js:24:17
at EventEmitter.<anonymous> (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/base-plugin.js:55:7)
at EventEmitter.<anonymous> (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/plugins/metronome/index.js:19:20)
at EventEmitter.eventsBus.emit (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/mainWorker.js:55:5)
at Socket.<anonymous> (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/build/main/plugins/bloq-eth-explorer/index.js:58:17)
at Socket.Emitter.emit (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-emitter/index.js:133:20)
at Socket.onevent (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/socket.io-client/lib/socket.js:270:10)
at Socket.onpacket (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/socket.io-client/lib/socket.js:228:12)
at Manager.<anonymous> (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-bind/index.js:21:15)
at Manager.Emitter.emit (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-emitter/index.js:133:20)
at Manager.ondecoded (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/socket.io-client/lib/manager.js:345:8)
at Decoder.<anonymous> (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-bind/index.js:21:15)
at Decoder.Emitter.emit (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-emitter/index.js:133:20)
at Decoder.add (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/socket.io-parser/index.js:241:12)
at Manager.ondata (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/socket.io-client/lib/manager.js:335:16)
at Socket.<anonymous> (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-bind/index.js:21:15)
at Socket.Emitter.emit (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-emitter/index.js:133:20)
at Socket.onPacket (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/engine.io-client/lib/socket.js:456:14)
at WS.<anonymous> (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/engine.io-client/lib/socket.js:273:10)
at WS.Emitter.emit (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/component-emitter/index.js:133:20)
at WS.Transport.onPacket (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/engine.io-client/lib/transport.js:145:8)
at WS.Transport.onData (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/engine.io-client/lib/transport.js:137:8)
at WebSocket.ws.onmessage (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
at WebSocket.onMessage (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/ws/lib/EventTarget.js:99:16)
at Receiver._receiver.onmessage (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/ws/lib/WebSocket.js:141:47)
at Receiver.dataMessage (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/ws/lib/Receiver.js:389:14)
at Receiver.getData (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/ws/lib/Receiver.js:330:12)
at Receiver.startLoop (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/ws/lib/Receiver.js:165:16)
at Receiver.add (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/ws/lib/Receiver.js:139:10)
at TLSSocket._ultron.on (C:/Users/Richard/AppData/Local/Programs/metronome-desktop-wallet/resources/app.asar/node_modules/ws/lib/WebSocket.js:138:22)```

**Comment by rsostrow91** [comment]
Mr. Garzik,
There have been three developments since I wrote the note above:

1.  My Metronome wallet disappeared from your system. I was able to recover 
     it (**minus the Metronome Purchase Transaction**) using the Recovery Passphrase. 
     In the process, I noticed that;
2. When I brought up my Metronome Wallet, a red message flashed and then 
    disappeared from the very top center of my screen. The message said, 
    "**Could Not Sync to the Latest Block**". The message does not recur. If I hadn't
     been looking at the screen at the moment that the message appeared, I would 
     not have seen it at all. 
     The Wallet behaved normally in spite of the error and, since **I had had a 
     successful transaction of ETH into the wallet**, I had no reason (until now) to 
     suspect that something was wrong. Which brings us to the last development;
3. When I recovered my wallet last night at about 2:00 am, I was glad to see that
    the balance of ETH was the same as when I had last seen the wallet. I had 
    transferred 2.999118 ETH into the wallet (as shown in **My Wallet.jpg** above)
    and there it still was. 
    Upon opening my wallet this morning, to see if there had been any reaction to 
    my note, there were 2.9989976481 ETH in the  wallet; A difference of 0.000120319
    ETH. At this morning's price of ETH ($455.71) that works out to be about five cents
    ($0.054178814823). Now, you can have the 5 cents for all I care, but I would like an
    explanation as to where it went. If it is a fee, what possible transaction took place 
    that was worth even 5 cents? If it was not a fee, you have a bigger problem with 
    money being syphoned out of people's wallets. I'm looking forward to your answer.

Thank you for looking into this. Your comment is very brief and to the point: 
"Looks like toLowerCase error". What do I do to fix it?

I hope there are equally brief and to the point fixes for my problems.
Richard Ostrow

**Comment by rsostrow91** [comment]
** UPDATE TO BUG ** in Metronome Auction #25

Mr. Garzik,
There have been three developments since I wrote the note above:

   1. My Metronome wallet disappeared from your system. I was able to
   recover
   it (*minus the Metronome Purchase Transaction*) using the Recovery
   Passphrase.
   In the process, I noticed that;
   2. When I brought up my Metronome Wallet, a red message flashed and then
   disappeared from the very top center of my screen. The message said,
   "*Could Not Sync to the Latest Block*". The message does not recur. If I
   hadn't
   been looking at the screen at the moment that the message appeared, I
   would
   not have seen it at all.
   The Wallet behaved normally in spite of the error and, since
*I had had a successful transaction of ETH into the wallet*, I had no
   reason (until now) to
   suspect that something was wrong. Which brings us to the last
   development;
   3. When I recovered my wallet last night at about 2:00 am, I was glad to
   see that
   the balance of ETH was the same as when I had last seen the wallet. I had
   transferred 2.999118 ETH into the wallet (as shown in *My Wallet.jpg*
   above)
   and there it still was.
   Upon opening my wallet this morning, to see if there had been any
   reaction to
   my note, there were 2.9989976481 ETH in the wallet; A difference of
   0.000120319
   ETH. At this morning's price of ETH ($455.71) that works out to be about
   five cents
   ($0.054178814823). Now, you can have the 5 cents for all I care, but I
   would like an
   explanation as to where it went. If it is a fee, what possible
   transaction took place
   that was worth even 5 cents? If it was not a fee, you have a bigger
   problem with
   money being syphoned out of people's wallets. I'm looking forward to
   your answer.

Thank you for looking into this. Your comment is very brief and to the
point:
"Looks like toLowerCase error". What do I do to fix it?

I hope there are equally brief and to the point fixes for my problems.

Richard Stephen Ostrow

**Comment by rsostrow91** [comment]
You have three whole issues. How long does it take you to respond to one?
